### ISSUE TITLE
Thread Safty

### ISSUE THREAD

**Issue by devmondo** [darrencauthon/AppBus#1]
Hi, 
really cool library you have here, but may i ask if it is a thread safe one ?

**Comment by darrencauthon** [comment]
It is thread-safe in that it runs in the current thread, synchronously. :)

**Comment by devmondo** [comment]
awesome man, so bear with my amateurism knowledge
, say i have a Blog Module and i want to make it extendable, so i create a plugin System, and when for example i save the record in the Save Action in the controller, i want to use your library to send message to all IPlugin classes instances, and then send back the result Message to the save action and if it is success then continue saving if it is not through an exception.

so is this possible? and to be more specific this operation will be possible for each user without thread leaking ?

thanks again for your answer.

**Comment by darrencauthon** [comment]
Yeah, there's nothing in the code that is not thread-safe, as everything happens synchronously. 

To put it another way, there's no difference between you using your instances of IPlugin or of copy/pasting the plugin code directly into the controller.  AppBus just makes it easier to separate that code into single classes, and making an extension point for any other libraries that might want to hop in to the process as well.

**Comment by devmondo** [comment]
thank you so much man, i was in big doubt because i am not pro, you explained it very well :)

**Comment by darrencauthon** [comment]
Don't say it like that, I'm sure you're just a professional as anybody.  Good luck with the library!
